import Box from "@mui/material/Box";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Navbar from "./components/navbar";
import "./globals.css";

const drawerWidth = 240;

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Box sx={{ display: "flex", paddingTop: { xs: "4rem" } }}>
          <Navbar drawerWidth={drawerWidth} />
          <Box
            sx={{
              maxWidth: { xs: "100%", lg: `calc(100vw - ${drawerWidth}px)` },
              float: "none",
            }}
          >
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
